"""new fields in the user model

Revision ID: 11309b63ba4d
Revises: 09196249651d
Create Date: 2019-10-24 11:40:52.013317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11309b63ba4d'
down_revision = '09196249651d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=280), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
